version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 386757133791.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=386757133791.dkr.ecr.ap-southeast-1.amazonaws.com/aws-docker-myapp
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t myapp .
      - echo Installing Trivy for vulnerability scanning...
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      - echo Scanning Docker image with Trivy...
      - ./trivy image myapp --exit-code 1 --severity HIGH,CRITICAL

      # If scan passes, continue to tag
      - echo Tagging Docker image for ECR...
      - docker tag myapp:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions...
      - |
        printf '[{"name":"myapp","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json

