server.port=8080

#Point to Docker secret files (not using .txt)
spring.datasource.url=jdbc:mysql://mysql:3306/mydb
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#Health Check
management.endpoints.web.exposure.include=health,info





